# Generated by Django 5.0.7 on 2024-07-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para1', models.CharField(max_length=6000, null=True)),
                ('para2', models.CharField(max_length=6000, null=True)),
                ('service_1_title', models.CharField(max_length=200, null=True)),
                ('service_1_description', models.CharField(max_length=200, null=True)),
                ('service_2_title', models.CharField(max_length=200, null=True)),
                ('service_2_description', models.CharField(max_length=200, null=True)),
                ('service_3_title', models.CharField(max_length=200, null=True)),
                ('service_3_description', models.CharField(max_length=200, null=True)),
                ('service_4_title', models.CharField(max_length=200, null=True)),
                ('service_4_description', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200, null=True)),
                ('start_year', models.IntegerField(null=True)),
                ('end_year', models.IntegerField(null=True)),
                ('description', models.CharField(max_length=300, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('level_in_percent', models.IntegerField(null=True)),
                ('end_year', models.IntegerField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('message', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
