# Generated by Django 5.0.7 on 2024-07-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_about_education_skill_testimonials'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200, null=True)),
                ('start_year', models.IntegerField(null=True)),
                ('end_year', models.IntegerField(null=True)),
                ('description', models.CharField(max_length=300, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
