# Generated by Django 5.0.7 on 2024-07-23 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_myeducation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyEducation',
        ),
    ]
