# Generated by Django 5.0.7 on 2024-07-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_myeducation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exprience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, null=True)),
                ('start_year', models.IntegerField(null=True)),
                ('end_year', models.CharField(default='Present', max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='job',
            new_name='job_title',
        ),
        migrations.AlterField(
            model_name='about',
            name='para1',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='para2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='service_1_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='service_2_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='service_3_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='service_4_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
