# Generated by Django 5.0.7 on 2024-07-23 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_testimonials_testimonial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exprience',
            new_name='Experience',
        ),
    ]
