# Generated by Django 5.0.7 on 2024-07-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_profile_instagram_profile_linkedin_profile_province_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
