# Generated by Django 5.0.7 on 2024-07-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_profile_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200, null=True),
        ),
    ]
