# Generated by Django 5.0.7 on 2024-07-24 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_experience_job_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='end_year',
        ),
    ]
