# Generated by Django 5.0.7 on 2024-07-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_category_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='main_image',
        ),
        migrations.AddField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
