# Generated by Django 5.0.7 on 2024-07-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_project_main_image_project_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='by_default.jpg', null=True, upload_to=''),
        ),
    ]
