# Generated by Django 5.0.7 on 2024-07-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
